#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    args.language = "en_GB"
    args.with_carddav = 1


    test_upgrade_from.20635f12df8167966e0ae373d024334762df0d39.name = "1.6.15~ynh1"
